name: Android Build (Unsigned APK)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Android SDK Tools
      # You may pin to the exact commit or the version.
      # uses: Xmaxer/setup-android@a616bd45cef25af5fc21fb0daced4e7a77eca955
        uses: Xmaxer/setup-android@v1.0.3
      

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'

      - name: Install Dependencies
        run: npm ci

      - name: Ensure Android Assets Folders Exist
        run: |
          mkdir -p android/app/src/main/assets
          mkdir -p android/app/src/main/res
      
      # - name: Bundle Expo Router App for Android
      #   run: |
      #     npx react-native bundle \
      #       --platform android \
      #       --dev false \
      #       --entry-file node_modules/expo-router/entry.js \
      #       --bundle-output android/app/src/main/assets/index.android.bundle \
      #       --assets-dest android/app/src/main/res \
      #       --reset-cache \
      #       --verbose
      # - name: Bundle Expo Router App for Android
      #   run: |
      #     npx expo run:android --variant release

      - name: Build Unsigned APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Get artifact
          path: android/app/build/outputs/apk/release/*
